version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - uploads:/app/src/uploads

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE=http://localhost:4000

volumes:
  mongo_data:
  uploads:
